from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: CP-1
    Generated by: David Stiven leon (ldavidz1999@gmail.com)
    Generated on 04/12/2021, 06:20:27
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="PSc4r5iDlXSHMibj4jOOkVAqcnPHQniWynK3ymF4xf8",
                              project_name="My first Project",
                              job_name="CP-1")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://example.testproject.io/web/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Navigate to 'http://idiv-cloud.webcindario.com/'
    driver.get("http://idiv-cloud.webcindario.com/")

    # 3. Click 'Únete Ahora!'
    _nete_ahora_ = driver.find_element(By.XPATH,
                                       "//li/button[. = 'Únete Ahora!']")
    _nete_ahora_.click()

    # 4. Click 'nickname_usuario'
    nickname_usuario = driver.find_element(By.CSS_SELECTOR,
                                           "#nickname_usuario")
    nickname_usuario.click()

    # 5. Type 'PRC1' in 'nickname_usuario'
    nickname_usuario = driver.find_element(By.CSS_SELECTOR,
                                           "#nickname_usuario")
    nickname_usuario.send_keys("PRC1")

    # 6. Click 'correo_usuario'
    correo_usuario = driver.find_element(By.CSS_SELECTOR,
                                         "#correo_usuario")
    correo_usuario.click()

    # 7. Type 'prc1@gmail.com' in 'correo_usuario'
    correo_usuario = driver.find_element(By.CSS_SELECTOR,
                                         "#correo_usuario")
    correo_usuario.send_keys("prc1@gmail.com")

    # 8. Click 'contrasena_usuario'
    contrasena_usuario = driver.find_element(By.CSS_SELECTOR,
                                             "#contrasena_usuario")
    contrasena_usuario.click()

    # 9. Type '123456789' in 'contrasena_usuario'
    contrasena_usuario = driver.find_element(By.CSS_SELECTOR,
                                             "#contrasena_usuario")
    contrasena_usuario.send_keys("123456789")

    # 10. Click 'fecha_nac_usuario'
    fecha_nac_usuario = driver.find_element(By.CSS_SELECTOR,
                                            "#fecha_nac_usuario")
    fecha_nac_usuario.click()

    # 11. Type '1999-07-16' in 'fecha_nac_usuario'
    fecha_nac_usuario = driver.find_element(By.CSS_SELECTOR,
                                            "#fecha_nac_usuario")
    fecha_nac_usuario.send_keys("1999-07-16")

    # 12. Click 'id_pais_usuario'
    id_pais_usuario = driver.find_element(By.CSS_SELECTOR,
                                          "#id_pais_usuario")
    id_pais_usuario.click()

    # 13. Select the '52' option in 'id_pais_usuario'
    id_pais_usuario = driver.find_element(By.CSS_SELECTOR,
                                          "#id_pais_usuario")
    Select(id_pais_usuario).select_by_value("52")

    # 14. Click 'id_pais_usuario'
    id_pais_usuario = driver.find_element(By.CSS_SELECTOR,
                                          "#id_pais_usuario")
    id_pais_usuario.click()

    # 15. Click 'Registrarse'
    registrarse = driver.find_element(By.XPATH,
                                      "//button[. = 'Registrarse']")
    registrarse.click()

    # 16. Click 'Iniciar Sesion'
    iniciar_sesion = driver.find_element(By.XPATH,
                                         "//a[. = ' Iniciar Sesion']")
    iniciar_sesion.click()

    # 17. Click 'login_nickname_usuario'
    login_nickname_usuario = driver.find_element(By.CSS_SELECTOR,
                                                 "#login_nickname_usuario")
    login_nickname_usuario.click()

    # 18. Type 'PRC1' in 'login_nickname_usuario'
    login_nickname_usuario = driver.find_element(By.CSS_SELECTOR,
                                                 "#login_nickname_usuario")
    login_nickname_usuario.send_keys("PRC1")

    # 19. Click 'login_contrasena_usuario'
    login_contrasena_usuario = driver.find_element(By.CSS_SELECTOR,
                                                   "#login_contrasena_usuario")
    login_contrasena_usuario.click()

    # 20. Type '123456789' in 'login_contrasena_usuario'
    login_contrasena_usuario = driver.find_element(By.CSS_SELECTOR,
                                                   "#login_contrasena_usuario")
    login_contrasena_usuario.send_keys("123456789")

    # 21. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//i/input")
    input.click()

    # 22. Click 'I'
    i = driver.find_element(By.XPATH,
                            "//td[6]//i")
    i.click()
